# Generated by Django 4.2 on 2023-04-14 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_inventory'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inventory',
            table='invetory',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
