# Generated by Django 4.2 on 2023-04-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default=2, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('progress', 'Progress'), ('finished', 'Finished')], default='waiting', max_length=128),
        ),
        migrations.AlterModelTable(
            name='project',
            table='project',
        ),
    ]
