# Generated by Django 4.2 on 2023-04-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employee_is_interner'),
        ('project', '0002_project_name_project_status_alter_project_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='employess',
            field=models.ManyToManyField(related_name='employees', to='employee.employee'),
        ),
    ]
