# Generated by Django 4.2 on 2023-04-14 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0002_internship_delete_intership'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='internship',
            table='internship',
        ),
        migrations.AlterModelTable(
            name='traniee',
            table='traniee',
        ),
    ]
