# Generated by Django 4.2 on 2023-04-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='end_work',
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.FloatField(default=0),
        ),
    ]
