# Generated by Django 4.2 on 2023-04-14 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_remove_employee_end_work_employee_salary'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
