# Generated by Django 4.2 on 2023-04-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_interner',
            field=models.BooleanField(default=False),
        ),
    ]
