# Generated by Django 4.2 on 2023-04-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employee_is_interner'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='postion',
            field=models.CharField(default='developer', max_length=46),
            preserve_default=False,
        ),
    ]
