# Generated by Django 4.2 on 2023-04-14 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attandance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attandance',
            table='attandance',
        ),
    ]
