# Generated by Django 4.2 on 2023-04-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attandance', '0002_alter_attandance_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attandance',
            name='start_work',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
